apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-analyzer
  labels:
    app: image-analyzer
spec:
  replicas: 2  # Start with 2 pods
  selector:
    matchLabels:
      app: image-analyzer
  template:
    metadata:
      labels:
        app: image-analyzer
    spec:
      containers:
        - name: image-analyzer
          image: your-dockerhub-username/image-analyzer:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

