[tool.black]
line-length = 88
target-version = ["py39"]
exclude = '''
/(
    \.eggs|
    \.git|
    \.mypy_cache|
    \.tox|
    \.venv|
    build|
    dist
)/
'''
[tool.isort]
profile = "black"
line_length = 88
known_third_party = ["your_dependencies_here"]
skip = ["build", "dist", ".venv", "__pycache__"]
